import { db } from '@/db/client';
import { type Profile } from '@/types/profile';
import { v4 as uuidv4 } from 'uuid';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'openai/gpt-4o-mini'; // Cost-effective and capable

export async function parseResumeWithAI(resumeText: string): Promise<Profile> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing. Please configure it in Settings.");
    }

    const systemPrompt = `
    You are an expert resume parser. Your job is to extract structured data from a raw resume text and return it as a JSON object.
    
    Return ONLY valid JSON. No markdown formatting, no code blocks.
    
    The structure must strictly follow this TypeScript interface (excluding IDs, which I will generate):
    
    interface ParsedProfile {
        name: string; // The candidate's full name, inferred from the top of the resume.
        targetRole: string; // The candidate's current or target role title.
        intro: string; // A brief professional summary (2-3 sentences), synthesized from the resume.
        skills: string[]; // List of technical skills, languages, tools.
        experience: Array<{
            company: string;
            role: string;
            startDate: string; // e.g., "Jan 2020", "2020", or "Present"
            endDate: string; // e.g., "Jan 2022", "2022", or "Present". If still active, use "Present".
            current: boolean; // true if endDate is "Present"
            description: string; // A concise summary of responsibilities and achievements (max 300 chars).
        }>;
        projects: Array<{
            name: string;
            description: string; // Brief description of what it does and tech used.
            url?: string; // GitHub or live link if found.
        }>;
        education: Array<{
            institution: string;
            degree: string;
            startDate: string; // e.g. "2014"
            endDate: string; // e.g. "2018"
        }>;
        certifications: Array<{
            name: string;
            issuer: string;
            year: string;
        }>;
    }
    
    If any field is missing, use empty strings or empty arrays. Do not invent data.
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local', // Required by OpenRouter
                'X-Title': 'Personal Job OS', // Required by OpenRouter
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: resumeText }
                ],
                temperature: 0.1, // Low temp for deterministic output
                response_format: { type: 'json_object' } // Ensure JSON mode
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        const content = data.choices[0]?.message?.content;

        if (!content) {
            throw new Error("No content received from AI.");
        }

        const parsed: any = JSON.parse(content);

        // Transform into full Profile object (add IDs)
        const profile: Profile = {
            id: undefined, // Will be auto-generated by Dexie on add, or ignored
            name: parsed.name || 'Unknown Candidate',
            targetRole: parsed.targetRole || 'Job Seeker',
            intro: parsed.intro || '',
            skills: Array.isArray(parsed.skills) ? parsed.skills : [],
            experience: Array.isArray(parsed.experience) ? parsed.experience.map((e: any) => ({
                id: uuidv4(),
                company: e.company || 'Unknown',
                role: e.role || 'Unknown',
                startDate: e.startDate || '',
                endDate: e.endDate || '',
                current: !!e.current,
                description: e.description || ''
            })) : [],
            projects: Array.isArray(parsed.projects) ? parsed.projects.map((p: any) => ({
                id: uuidv4(),
                name: p.name || 'Unnamed Project',
                description: p.description || '',
                url: p.url || ''
            })) : [],
            education: Array.isArray(parsed.education) ? parsed.education.map((e: any) => ({
                id: uuidv4(),
                institution: e.institution || '',
                degree: e.degree || '',
                startDate: e.startDate || '',
                endDate: e.endDate || ''
            })) : [],
            certifications: Array.isArray(parsed.certifications) ? parsed.certifications.map((c: any) => ({
                id: uuidv4(),
                name: c.name || '',
                issuer: c.issuer || '',
                year: c.year || '',
                url: ''
            })) : [],
            updatedAt: new Date(),
        };

        return profile;

    } catch (error) {
        console.error("AI Parse Error:", error);
        throw error;
    }
}

export async function generateResumeDraft(profile: Profile, jobDetails: { company: string; role: string; description: string }): Promise<string> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing. Please configure it in Settings.");
    }

    const systemPrompt = `
    You are an expert resume writer. Your goal is to tailor a candidate's profile to a specific job description.
    
    You will be given:
    1. The Candidate's Profile (JSON)
    2. The Job Details (Company, Role, Description)
    
    Output:
    A complete, plain-text resume formatted in Markdown. 
    - Focus on relevant skills and experience.
    - Rewrite the summary to align with the job.
    - Reorder or highlight bullet points that match the job requirements.
    - Do NOT invent false information, but emphasize truthful relevant details.
    `;

    const userPrompt = `
    PROFILE:
    ${JSON.stringify(profile, null, 2)}
    
    JOB DETAILS:
    Company: ${jobDetails.company}
    Role: ${jobDetails.role}
    Description:
    ${jobDetails.description}
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local',
                'X-Title': 'Personal Job OS',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                temperature: 0.7 // Slightly higher creativity for writing
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        let content = data.choices[0]?.message?.content || "Failed to generate resume.";

        // Strip code blocks if present (e.g. ```markdown ... ```)
        content = content.replace(/^```markdown\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/, '');

        return content;

    } catch (error) {
        console.error("AI Gen Error:", error);
        throw error;
    }
}

export async function refineResume(currentResume: string, instructions: string): Promise<string> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing.");
    }

    const systemPrompt = `
    You are an expert resume editor. You will refine an existing resume draft based on specific user instructions.
    Return the FULL updated resume text in Markdown. Do not return just the diff.
    Do NOT include markdown formatted code blocks (e.g. \`\`\`markdown). Just return the content.
    `;

    const userPrompt = `
    CURRENT RESUME:
    ${currentResume}
    
    INSTRUCTIONS:
    ${instructions}
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local',
                'X-Title': 'Personal Job OS',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                temperature: 0.5
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        let content = data.choices[0]?.message?.content || "Failed to refine resume.";

        // Strip code blocks if present
        content = content.replace(/^```markdown\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/, '');

        return content;

    } catch (error) {
        console.error("AI Refine Error:", error);
        throw error;
    }
}
