import { db } from '@/db/client';
import { type Profile } from '@/types/profile';
import { v4 as uuidv4 } from 'uuid';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'openai/gpt-4o-mini'; // Cost-effective and capable

export async function parseResumeWithAI(resumeText: string): Promise<Profile> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing. Please configure it in Settings.");
    }

    const systemPrompt = `
    You are an expert resume parser. Your job is to extract structured data from a raw resume text and return it as a JSON object.
    
    Return ONLY valid JSON. No markdown formatting, no code blocks.
    
    The structure must strictly follow this TypeScript interface (excluding IDs, which I will generate):
    
    interface ParsedProfile {
        name: string;
        targetRole: string;
        intro: string;
        skills: string[];
        contactInfo: {
            email: string;
            phone: string;
            location: string;
            linkedin: string;
            github: string;
            website: string;
        };
        hrData: {
            noticePeriod: string; // e.g. "Immediate", "2 weeks", "3 months"
            workPreference: string; // e.g. "Remote", "Hybrid", "On-site" (Infer if possible)
        };
        experience: Array<{
            company: string;
            role: string;
            startDate: string;
            endDate: string;
            current: boolean;
            description: string;
        }>;
        projects: Array<{
            name: string;
            description: string;
            url?: string;
        }>;
        education: Array<{
            institution: string;
            degree: string;
            startDate: string;
            endDate: string;
        }>;
        certifications: Array<{
            name: string;
            issuer: string;
            year: string;
        }>;
    }
    
    If any field is missing, use empty strings or empty arrays. Do not invent data.
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local', // Required by OpenRouter
                'X-Title': 'Personal Job OS', // Required by OpenRouter
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: resumeText }
                ],
                temperature: 0.1, // Low temp for deterministic output
                response_format: { type: 'json_object' } // Ensure JSON mode
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        const content = data.choices[0]?.message?.content;

        if (!content) {
            throw new Error("No content received from AI.");
        }

        const parsed: any = JSON.parse(content);

        // Transform into full Profile object (add IDs)
        const profile: Profile = {
            id: undefined, // Will be auto-generated by Dexie on add, or ignored
            name: parsed.name || 'Unknown Candidate',
            targetRole: parsed.targetRole || 'Job Seeker',
            intro: parsed.intro || '',
            skills: Array.isArray(parsed.skills) ? parsed.skills : [],
            contactInfo: {
                email: parsed.contactInfo?.email || '',
                phone: parsed.contactInfo?.phone || '',
                location: parsed.contactInfo?.location || '',
                linkedin: parsed.contactInfo?.linkedin || '',
                github: parsed.contactInfo?.github || '',
                website: parsed.contactInfo?.website || '',
            },
            hrData: {
                noticePeriod: parsed.hrData?.noticePeriod || '',
                workPreference: parsed.hrData?.workPreference || '',
            },
            experience: Array.isArray(parsed.experience) ? parsed.experience.map((e: any) => ({
                id: uuidv4(),
                company: e.company || 'Unknown',
                role: e.role || 'Unknown',
                startDate: e.startDate || '',
                endDate: e.endDate || '',
                current: !!e.current,
                description: e.description || ''
            })) : [],
            projects: Array.isArray(parsed.projects) ? parsed.projects.map((p: any) => ({
                id: uuidv4(),
                name: p.name || 'Unnamed Project',
                description: p.description || '',
                url: p.url || ''
            })) : [],
            education: Array.isArray(parsed.education) ? parsed.education.map((e: any) => ({
                id: uuidv4(),
                institution: e.institution || '',
                degree: e.degree || '',
                startDate: e.startDate || '',
                endDate: e.endDate || ''
            })) : [],
            certifications: Array.isArray(parsed.certifications) ? parsed.certifications.map((c: any) => ({
                id: uuidv4(),
                name: c.name || '',
                issuer: c.issuer || '',
                year: c.year || '',
                url: ''
            })) : [],
            updatedAt: new Date(),
        };

        return profile;

    } catch (error) {
        console.error("AI Parse Error:", error);
        throw error;
    }
}

export async function generateResumeDraft(profile: Profile, jobDetails: { company: string; role: string; description: string }): Promise<string> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing. Please configure it in Settings.");
    }

    const systemPrompt = `
    You are an expert resume writer. Your goal is to tailor a candidate's profile to a specific job description.
    
    You will be given:
    1. The Candidate's Profile (JSON)
    2. The Job Details (Company, Role, Description)
    
    Output:
    A complete, plain-text resume formatted in Markdown.     - **CRITICAL**: The output must start IMMEDIATELY with the **## Professional Summary** header (Use H2).
    - **CRITICAL**: You MUST use H2 headers (##) for all main sections to ensure proper styling.
    - **CRITICAL**: You MUST include the following sections in this order:
      1. ## Professional Summary
      2. ## Skills
      3. ## Experience
      4. ## Projects
      5. ## Education
    - **Format Experience** exactly like this (Use H3 for roles):
      ### Role Title | Start Date - End Date
      **Company Name**
      *   Bullet point...
    - **CRITICAL**: Do NOT output the candidate's Name, Phone, Email, Location, or Links. This is handled externally.
    - **CRITICAL**: Do NOT add an "Additional Information" section. Integrate soft skills into the Experience descriptions.
    - **CRITICAL**: Do NOT add a concluding paragraph (e.g., "This resume aligns with..."). End strictly with the last section.
    - Focus on relevant skills and experience.
    - Rewrite the summary to align with the job.
    `;

    const userPrompt = `
    PROFILE:
    ${JSON.stringify(profile, null, 2)}
    
    JOB DETAILS:
    Company: ${jobDetails.company}
    Role: ${jobDetails.role}
    Description:
    ${jobDetails.description}
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local',
                'X-Title': 'Personal Job OS',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                temperature: 0.7 // Slightly higher creativity for writing
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        let content = data.choices[0]?.message?.content || "Failed to generate resume.";

        // Strip code blocks if present (e.g. ```markdown ... ```)
        content = content.replace(/^```markdown\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/, '');

        // Defensive cleanup: Check for section headers to remove intro fluff
        const firstHeaderMatch = content.match(/^(#+\s*(Professional Summary|Summary|Skills|Experience))/im);
        if (firstHeaderMatch && firstHeaderMatch.index && firstHeaderMatch.index > 0) {
            content = content.substring(firstHeaderMatch.index);
        }

        // Defensive cleanup: Remove AI conclusion fluff at the end
        const fluffPatterns = [
            /This resume aligns (closely|well) with/i,
            /This resume has been (tailored|optimized) for/i,
            /I have highlighted (the|your)/i,
            /The above resume/i,
            /Please let me know if/i
        ];
        const lines = content.split('\n');
        for (let i = lines.length - 1; i >= Math.max(0, lines.length - 10); i--) {
            if (fluffPatterns.some(p => p.test(lines[i]))) {
                // Cut everything from here
                content = lines.slice(0, i).join('\n').trim();
                break;
            }
        }

        return content;
    } catch (error) {
        console.error("AI Gen Error:", error);
        throw error;
    }
}

export async function refineResume(currentResume: string, instructions: string): Promise<string> {
    const settings = await db.settings.toCollection().first();
    const apiKey = settings?.openRouterApiKey;

    if (!apiKey) {
        throw new Error("OpenRouter API Key is missing.");
    }

    const systemPrompt = `
    You are an expert resume editor. You will refine an existing resume draft based on specific user instructions.
    Return the FULL updated resume text in Markdown. Do not return just the diff.
    Do NOT include markdown formatted code blocks (e.g. \`\`\`markdown). Just return the content.
    **CRITICAL RULES**:
    1. Do NOT include or re-add the contact header (Name, Phone, etc.) at the top. Start with the Summary.
    2. Do NOT add an "Additional Information" section.
    3. **CRITICAL**: Use \`##\` (H2) for all main section headers (Summary, Skills, Experience, Projects, Education) to maintain styling.
    4. **Format Experience** exactly like this (Use H3):
       ### Role Title | Start Date - End Date
       **Company Name**
       *   Bullet point...
    5. Maintain a professional tone.
    6. **CRITICAL**: Do NOT add a concluding paragraph (e.g., "This resume aligns with..."). Return ONLY the resume content.
    `;

    const userPrompt = `
    CURRENT RESUME:
    ${currentResume}
    
    INSTRUCTIONS:
    ${instructions}
    `;

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'HTTP-Referer': 'https://jobos.local',
                'X-Title': 'Personal Job OS',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                temperature: 0.5
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`AI Request Failed: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        let content = data.choices[0]?.message?.content || "Failed to refine resume.";

        // Strip code blocks if present
        content = content.replace(/^```markdown\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/, '');

        // Defensive cleanup: Check for section headers to remove intro fluff
        const firstHeaderMatch = content.match(/^(#+\s*(Professional Summary|Summary|Skills|Experience))/im);
        if (firstHeaderMatch && firstHeaderMatch.index && firstHeaderMatch.index > 0) {
            // Keep everything starting from the match
            content = content.substring(firstHeaderMatch.index);
        }

        return content;
    } catch (error) {
        console.error("AI Refine Error:", error);
        throw error;
    }
}
